In [6]:
import torch

In [7]:
torch.rand(5,6)

tensor([[0.2292, 0.1350, 0.8107, 0.7255, 0.1938, 0.8461],
        [0.9200, 0.5779, 0.0777, 0.6148, 0.2860, 0.7176],
        [0.7892, 0.6376, 0.9285, 0.6603, 0.7397, 0.5707],
        [0.5091, 0.0270, 0.2052, 0.5251, 0.0254, 0.6762],
        [0.2213, 0.6261, 0.4782, 0.0112, 0.9302, 0.5990]])

In [14]:
x = torch.zeros(5,3, dtype=torch.float64)

In [15]:
x.dtype

torch.float64

In [16]:
torch.tensor([6,3])

tensor([6, 3])

In [17]:
x.new_ones(4,6, dtype=torch.double)

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]], dtype=torch.float64)

In [18]:
torch.randn_like(x)

tensor([[ 0.8344,  0.3689,  0.5817],
        [ 0.9911,  0.8357, -1.0920],
        [-0.5687, -1.7235, -0.5626],
        [ 0.0032, -2.5691, -1.7272],
        [ 0.0361,  0.6594,  0.4020]], dtype=torch.float64)

In [19]:
x.shape

torch.Size([5, 3])

In [20]:
x.size()

torch.Size([5, 3])

In [21]:
y = torch.rand(5,6)

In [26]:
y

tensor([[0.7412, 0.0081, 0.2437, 0.3743, 0.2763, 0.3335],
        [0.8467, 0.6248, 0.3815, 0.8449, 0.9030, 0.3310],
        [0.2056, 0.8337, 0.4145, 0.9658, 0.3493, 0.3806],
        [0.0148, 0.3461, 0.8356, 0.2252, 0.2937, 0.4010],
        [0.9095, 0.1822, 0.7932, 0.7497, 0.8764, 0.9266]])

In [28]:
x = y.new_ones(5,6)

In [30]:
y + x

tensor([[1.7412, 1.0081, 1.2437, 1.3743, 1.2763, 1.3335],
        [1.8467, 1.6248, 1.3815, 1.8449, 1.9030, 1.3310],
        [1.2056, 1.8337, 1.4145, 1.9658, 1.3493, 1.3806],
        [1.0148, 1.3461, 1.8356, 1.2252, 1.2937, 1.4010],
        [1.9095, 1.1822, 1.7932, 1.7497, 1.8764, 1.9266]])

In [31]:
y.add_(x)

tensor([[1.7412, 1.0081, 1.2437, 1.3743, 1.2763, 1.3335],
        [1.8467, 1.6248, 1.3815, 1.8449, 1.9030, 1.3310],
        [1.2056, 1.8337, 1.4145, 1.9658, 1.3493, 1.3806],
        [1.0148, 1.3461, 1.8356, 1.2252, 1.2937, 1.4010],
        [1.9095, 1.1822, 1.7932, 1.7497, 1.8764, 1.9266]])

In [32]:
y

tensor([[1.7412, 1.0081, 1.2437, 1.3743, 1.2763, 1.3335],
        [1.8467, 1.6248, 1.3815, 1.8449, 1.9030, 1.3310],
        [1.2056, 1.8337, 1.4145, 1.9658, 1.3493, 1.3806],
        [1.0148, 1.3461, 1.8356, 1.2252, 1.2937, 1.4010],
        [1.9095, 1.1822, 1.7932, 1.7497, 1.8764, 1.9266]])

In [33]:
x

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [38]:
 x[1:2, 4:]

tensor([[1., 1.]])

In [41]:
y = torch.randn(4,5)

In [46]:
y.view(20)

tensor([ 0.7833, -0.6409, -1.6142, -0.6345,  0.6283,  0.6767,  0.9754, -0.4390,
         0.2412,  0.2938,  2.0690,  0.5958,  1.7991,  1.5130,  1.3378, -0.1267,
         0.6029, -0.0686,  0.9219,  0.2303])

In [48]:
y.view(5,4)

tensor([[ 0.7833, -0.6409, -1.6142, -0.6345],
        [ 0.6283,  0.6767,  0.9754, -0.4390],
        [ 0.2412,  0.2938,  2.0690,  0.5958],
        [ 1.7991,  1.5130,  1.3378, -0.1267],
        [ 0.6029, -0.0686,  0.9219,  0.2303]])

In [49]:
y.reshape(4,5)

tensor([[ 0.7833, -0.6409, -1.6142, -0.6345,  0.6283],
        [ 0.6767,  0.9754, -0.4390,  0.2412,  0.2938],
        [ 2.0690,  0.5958,  1.7991,  1.5130,  1.3378],
        [-0.1267,  0.6029, -0.0686,  0.9219,  0.2303]])

In [50]:
y.item()

ValueError: only one element tensors can be converted to Python scalars

In [51]:
y.numpy()

array([[ 0.7832891 , -0.6408733 , -1.6141915 , -0.63453555,  0.6282577 ],
       [ 0.67665845,  0.97536296, -0.43903378,  0.24119812,  0.29378626],
       [ 2.0690277 ,  0.5958466 ,  1.7991316 ,  1.5130469 ,  1.337807  ],
       [-0.12668899,  0.60289216, -0.06861991,  0.9218989 ,  0.23026417]],
      dtype=float32)

In [53]:
import numpy as np

In [54]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [55]:
  1e-6

1e-06

In [73]:
N, D_in, H, D_out = 64, 1000, 100, 10
X = np.random.randn(N, D_in)
Y = np.random.randn(N, D_out)

w1 = np.random.randn(D_in, H)
w2 = np.random.randn(H, D_out)
learning_rate = 1e-6

In [74]:
for it in range(500):
    h = X.dot(w1)
    h_relu = np.maximum(h, 0)
    y_pred = h_relu.dot(w2)
    
    loss = np.square(y_pred - Y).sum()
    print(it, loss)
    
    grad_y_pred = 2.0 * (y_pred - Y)
    grad_w2 = h_relu.T.dot(grad_y_pred)
    grad_h_relu = grad_y_pred.dot(w2.T)
    grad_h = grad_h_relu.copy()
    grad_h[h<0] = 0
    grad_w1 = X.T.dot(grad_h)
    
    w1 -= learning_rate * grad_w1
    w2 -= learning_rate * grad_w2

0 28325546.356411785
1 23766889.946754962
2 24885306.34988711
3 27931168.3367069
4 29558753.254335977
5 26788499.4589316
6 19893746.26164323
7 12153911.137704672
8 6538990.375462111
9 3404476.1325306008
10 1887075.6372465733
11 1171379.2980040354
12 818946.536206949
13 626598.5225529217
14 507580.17443553824
15 424925.3652007735
16 362514.48760269396
17 312828.2649274154
18 271977.0258907848
19 237724.41090070546
20 208688.95213838795
21 183887.10466456373
22 162573.13138484728
23 144232.38409222144
24 128348.61457709804
25 114510.7611242932
26 102440.66851175643
27 91851.4610566744
28 82530.47007599594
29 74308.35711328275
30 67034.04939577862
31 60576.771201747826
32 54840.45237301663
33 49726.032499332294
34 45158.71192423644
35 41071.82628380288
36 37407.08759593342
37 34114.03301714073
38 31149.37487911131
39 28475.704801654945
40 26061.610343879373
41 23880.477537782564
42 21905.058600085413
43 20118.455973007563
44 18495.400637130922
45 17019.67285390047
46 15676.510847641697
47

423 3.6329248815887894e-05
424 3.468903324512189e-05
425 3.312315192261937e-05
426 3.1628626597346996e-05
427 3.0201690098289034e-05
428 2.8839473102093877e-05
429 2.7538793139155223e-05
430 2.629720571593918e-05
431 2.51121810757902e-05
432 2.3980668878366273e-05
433 2.290060242811345e-05
434 2.1869572635366005e-05
435 2.0885020509531886e-05
436 1.9944909479022452e-05
437 1.9047414785887907e-05
438 1.819060883293582e-05
439 1.737248528215417e-05
440 1.6591294718438365e-05
441 1.584586514633947e-05
442 1.5133870724569075e-05
443 1.4453890265197835e-05
444 1.3804705524382511e-05
445 1.3184832934498527e-05
446 1.2592960262766971e-05
447 1.2027712041016767e-05
448 1.1488130624810408e-05
449 1.0972997208651181e-05
450 1.0480847501688197e-05
451 1.0010956605015559e-05
452 9.562228696586963e-06
453 9.133736834442277e-06
454 8.724489503597751e-06
455 8.333719381092108e-06
456 7.960667590079697e-06
457 7.604351260142313e-06
458 7.2640042091767366e-06
459 6.938952404781539e-06
460 6.62856082361